parameters:
#    pg_news.example.class: PG\NewsBundle\Example

services:
#    pg_news.example:
#        class: %pg_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pg_news.image_type_extension:
        class: PG\NewsBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }